server:
  port: 8080
  undertow:
    threads:
      io: 100
      worker: 1000
    accesslog:
      dir: './log'
      enabled: true # Whether to enable the access log.
      pattern: '%t %a "%r" %s (%D ms)' # Format pattern for access logs.
      prefix: 'access_log.' # Log file name prefix.
      suffix: 'log' # Log file name suffix.

spring:
  task:
    execution:
      pool:
        core-size: 400
        max-size: 400
  datasource:
    #url: jdbc:h2:tcp://localhost:1521/~/test
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update # 테이블 자동 생성 여부 (update : 자동 생성, none : 생성 안함)
    showSql: true
  h2:
    console:
      enabled: true